### ISSUE TITLE
Can't connect to ksmbd server

### ISSUE THREAD

**Issue by escapezn** [wa2c/cifs-documents-provider#12]
I'm using ksmbd as smb server on an openwrt device

This is ksmbd's config
```
[global]
        netbios name = kvvm
        server string = Ksmbd on OpenWrt
        workgroup = WORKGROUP
        interfaces = br-lan
        bind interfaces only = no
        ipc timeout = 20
        deadtime = 15
        map to guest = Bad User
        smb2 max read = 64K
        smb2 max write = 64K
        smb2 max trans = 64K
        cache read buffers = no
        cache trans buffers = no

######### Dynamic written config options #########

[music]
        path = /opt
        valid users = kvvm
        create mask = 0666
        directory mask = 0777
        read only = no
        guest ok = no
```

Windows 10 explorer and X-plore filemanager on Android both went well with this setup, but CIFS proveder never worked for it, simply toasting connection failed.

![Screenshot_20211203-115149](https://user-images.githubusercontent.com/30799958/144542646-723adbb4-31d0-4d59-8fcc-0a2057dec094.png)

Likely there are some compatibility issues, please have a look at this problem.

**Comment by wa2c** [comment]
@escapezn 
I changed a authentication code.
But I don't know if this fix solved this problem.
Can you try this and see if it has been fixed?

**Comment by escapezn** [comment]
Unfortunately the beta version doesn't fix this problem.

**Comment by wa2c** [comment]
OK, I will continue to check.

**Comment by wa2c** [comment]
@escapezn 
I released 1.4.0 new beta test version on Google Play.
It is improved some problems.

**Comment by escapezn** [comment]
The new beta still failed to connect but with [TreeID is invalid] in toast message.
